import { IMAGE_LOADER, NgOptimizedImage, type ImageLoaderConfig } from '@angular/common';
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { TranslocoDirective } from '@jsverse/transloco';
import { Button } from '../../shared/ui/button/button';

type ImageMode = 'unoptimized' | 'optimized';

const IMAGE_BASE = '/labs/images';
/** The widths generated by perf/generate-lab-images.ts. */
export const IMAGE_WIDTHS = [400, 800, 1600] as const;
export const IMAGE_COUNT = 12;

/**
 * Maps a requested width to the smallest generated file at least that wide.
 *
 * A real deployment points `IMAGE_LOADER` at an image CDN that resizes on
 * request; this repository has three files per picture, so the loader picks
 * among them. The `item` query parameter only makes each card a distinct URL,
 * as distinct photographs would be.
 */
export function labImageLoader(config: ImageLoaderConfig): string {
  const width = IMAGE_WIDTHS.find((candidate) => candidate >= (config.width ?? 0)) ?? 1600;
  return `${IMAGE_BASE}/photo-${width}.webp?item=${config.src}`;
}

/**
 * The same twelve pictures, two ways.
 *
 *  - **unoptimized**: a plain `<img>` of the original upload - a 1200 px PNG -
 *    with no dimensions, loaded eagerly whatever its position on the page;
 *  - **optimized**: `NgOptimizedImage` - a WebP at the width the layout needs
 *    (`srcset` + `sizes`, resolved per device pixel ratio), `loading="lazy"`
 *    for everything below the fold, `width`/`height` so the layout does not
 *    jump when it arrives, and `fetchpriority="high"` on the first, likely
 *    the largest contentful paint.
 *
 * The grid scrolls inside its own box, so most cards start off-screen and
 * lazy loading has something to decline.
 */
@Component({
  selector: 'app-image-demo',
  imports: [Button, NgOptimizedImage, TranslocoDirective],
  providers: [{ provide: IMAGE_LOADER, useValue: labImageLoader }],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="demo" *transloco="let t; prefix: 'pages.labs.performance.images'">
      <div class="demo__controls">
        <app-button data-testid="images-unoptimized" (click)="mode.set('unoptimized')">
          {{ t('unoptimized') }}
        </app-button>
        <app-button data-testid="images-optimized" (click)="mode.set('optimized')">
          {{ t('optimized') }}
        </app-button>
      </div>

      @if (mode(); as current) {
        <ul class="grid" data-testid="image-grid" [attr.data-mode]="current">
          @for (item of items; track item) {
            <li class="grid__card">
              @if (current === 'optimized') {
                <img
                  [ngSrc]="item"
                  width="1600"
                  height="1067"
                  [sizes]="sizes"
                  [priority]="$first"
                  [alt]="t('alt', { item: item })"
                />
              } @else {
                <img [src]="originalFor(item)" [alt]="t('alt', { item: item })" />
              }
            </li>
          }
        </ul>
      }
    </div>
  `,
  styles: `
    .demo {
      display: flex;
      flex-direction: column;
      gap: var(--space-3);
    }

    .demo__controls {
      display: flex;
      flex-wrap: wrap;
      gap: var(--space-2);
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(16rem, 1fr));
      gap: var(--space-2);
      height: 24rem;
      margin: 0;
      padding: 0;
      overflow-y: auto;
      list-style: none;
    }

    img {
      display: block;
      width: 100%;
      height: auto;
      border-radius: var(--radius-md);
    }
  `,
})
export class ImageDemo {
  /** The rendered width per viewport - what `srcset` candidates are chosen against. */
  protected readonly sizes = '(max-width: 600px) 90vw, 16rem';
  protected readonly mode = signal<ImageMode | null>(null);
  protected readonly items = Array.from({ length: IMAGE_COUNT }, (_, index) => String(index + 1));

  protected originalFor(item: string): string {
    return `${IMAGE_BASE}/photo-original.png?item=${item}`;
  }
}
